[package]
name = "nimc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
#log = { version = "0.4.27", features = ["release_max_level_warn"] }
log = "0.4.27"
simplelog = "0.12.2"
